# Generated by Django 3.0.7 on 2020-06-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=200, verbose_name='Номер контракта')),
                ('price', models.FloatField(verbose_name='НМЦК')),
                ('paid', models.FloatField(blank=True, null=True, verbose_name='Оплачено')),
                ('prev_paid', models.FloatField(blank=True, null=True)),
                ('prev_date_changed', models.DateTimeField()),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=200, verbose_name='Номер заявки')),
                ('order_subject', models.CharField(max_length=200, verbose_name='Предмет заявки')),
                ('price', models.FloatField(verbose_name='НМЦК')),
                ('prev_date_changed', models.DateTimeField()),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
