# Generated by Django 3.0.7 on 2020-06-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='prev_date_changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='prev_date_changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
