# Generated by Django 3.0.7 on 2020-06-15 12:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('parser_app', '0002_auto_20200615_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата заключения контракта'),
            preserve_default=False,
        ),
    ]
