# Generated by Django 3.0.7 on 2020-06-16 10:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('parser_app', '0003_contract_contract_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата заявки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Статус заявки'),
            preserve_default=False,
        ),
    ]
