# Generated by Django 3.0.7 on 2020-06-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('parser_app', '0004_auto_20200616_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prev_order_status',
            field=models.CharField(default=' ', max_length=200, verbose_name='Предыдущий статус заявки'),
            preserve_default=False,
        ),
    ]
