# Generated by Django 3.0.7 on 2020-06-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('parser_app', '0005_order_prev_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='prev_order_status',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Предыдущий статус заявки'),
        ),
    ]
