# Generated by Django 3.0.7 on 2020-06-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('parser_app', '0006_auto_20200616_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='НМЦК'),
        ),
    ]
