# Generated by Django 3.0.7 on 2020-06-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('parser_app', '0007_auto_20200616_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_successful_update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_subject',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Предмет заявки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='НМЦК'),
        ),
    ]
