# Generated by Django 3.0.7 on 2020-06-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('parser_app', '0008_auto_20200617_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_subject',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Предмет заявки'),
        ),
    ]
