# Generated by Django 3.0.7 on 2020-07-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('parser_app', '0009_auto_20200618_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заявки'),
        ),
    ]
