# Generated by Django 3.0.7 on 2020-10-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('parser_app', '0011_auto_20201006_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='last_contracts_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='last_orders_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
